name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  push:
    paths:
      - '**.agda'
      - '*.agda-lib'
      - '.github/workflows/**.yml'
    branches: [master]
  pull_request:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@v2
        with:
          agda-version: 2.7.0
          stdlib-version: 2.1.1
          main: Classes
          deploy: ${{ github.ref == 'refs/heads/master' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          measure-typechecking: true
